# Generated by Django 5.2.16 on 2026-09-12 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=14, unique=True)),
                ('nome_produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='avarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(max_length=100)),
                ('descricao_avaria', models.TextField()),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaria.produto')),
            ],
        ),
    ]
